// import { Inter } from 'next/font/google'
// import './globals.css'
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primeflex/primeflex.css";
import 'primeicons/primeicons.css';

export const metadata = {
  title: 'Todo Pro',
  description: 'Todo Portal',
}


// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <PrimeReactProvider>
    <html lang="en">
      <body>{children}</body>
    </html>
  </PrimeReactProvider>
  )
}
